# Generated by Django 5.0.6 on 2024-06-23 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
