# Generated by Django 5.0.6 on 2024-06-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_remove_userprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
