# Generated by Django 5.0.6 on 2024-06-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_candidate_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='phone_number',
        ),
    ]
