# Generated by Django 5.0.6 on 2024-06-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_candidate_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
    ]
