# Generated by Django 5.0.6 on 2024-06-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_alter_candidate_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
