# Generated by Django 5.0.6 on 2024-06-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_alter_candidate_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='qualification',
            field=models.CharField(default='', max_length=255),
        ),
    ]
