# Generated by Django 5.0.6 on 2024-06-25 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_candidate_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
    ]
