# Generated by Django 5.0.6 on 2024-06-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_remove_userprofile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='posted_date',
        ),
    ]
